### ISSUE TITLE
Compiling on raspberry pi 3

### ISSUE THREAD

**Issue by OctAg0nO** [ernw/ss7MAPer#1]
==> Entering directory `/home/pi/ss7MAPer/deps/osmo_ss7'
==> Entering directory`/home/pi/ss7MAPer/deps/epcap'
==> Entering directory `/home/pi/ss7MAPer/deps/pkt'
==> pkt (compile)
==> Leaving directory`/home/pi/ss7MAPer/deps/pkt'
==> epcap (compile)
ERROR: compile failed while processing /home/pi/ss7MAPer/deps/epcap: {'EXIT',
    {function_clause,
        [{rebar_port_compiler,filter_port_spec,"e",
             [{file,"src/rebar_port_compiler.erl"},{line,266}]},
         {rebar_port_compiler,'-filter_port_specs/1-lc$^0/1-0-',1,
             [{file,"src/rebar_port_compiler.erl"},{line,264}]},
         {rebar_port_compiler,get_port_specs,2,
             [{file,"src/rebar_port_compiler.erl"},{line,259}]},
         {rebar_port_compiler,get_specs,2,
             [{file,"src/rebar_port_compiler.erl"},{line,255}]},
         {rebar_port_compiler,compile,2,
             [{file,"src/rebar_port_compiler.erl"},{line,106}]},
         {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,425}]},
         {rebar_core,execute,5,[{file,"src/rebar_core.erl"},{line,359}]},
         {rebar_core,process_dir0,6,
             [{file,"src/rebar_core.erl"},{line,223}]}]}}

**Comment by OctAg0nO** [comment]
ok, i copy the pkt.hrl file from /deps/pkt/src in to /deps/epcap but i get other error.

pi@raspberrypi:~/ss7MAPer $ rebar co
==> pkt (compile)
==> epcap (compile)
ERROR: compile failed while processing /home/pi/ss7MAPer/deps/epcap: {'EXIT',{{badmatch,{error,eacces}},
         [{rebar_erlc_compiler,store_erlcinfo,2,
                               [{file,"src/rebar_erlc_compiler.erl"},
                                {line,490}]},
          {rebar_erlc_compiler,init_erlcinfo,2,
                               [{file,"src/rebar_erlc_compiler.erl"},
                                {line,392}]},
          {rebar_erlc_compiler,doterl_compile,4,
                               [{file,"src/rebar_erlc_compiler.erl"},
                                {line,302}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,493}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,418}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,302}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,261}]},
          {rebar_core,process_each,5,
                      [{file,"src/rebar_core.erl"},{line,351}]}]}}

**Comment by 0xc0decafe** [comment]
Hi,

which version of erl are you using?

cheers

**Comment by OctAg0nO** [comment]
Erlang/OTP 18 [erts-7.3] [source] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

**Comment by OctAg0nO** [comment]
?

**Comment by 0xc0decafe** [comment]
Hi,

as I just discovered, there seems to be a problem when building the deps on erlang >= 18.0. Working on it.

cheers

**Comment by OctAg0nO** [comment]
working on kali 2016.2 x64

im new in this area, mobile network, etc,
need a litter help here.

CONFIG

Last but not least in the target section information about the tested environment need to be configured, like the global title of the HLR, or the MSISDN of the tested phone.

where or how i can get that info ?
thats the only part need to modify for local test ?
