### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by HaxorGaruda** [ernw/ss7MAPer#11]
i has successful compile from source with erlang 18.3, but on readme, after compile still need to run binary release on bin/ folder, on install from source, nothing folder bin on ss7mapper folder, and nothing on /usr/bin or /usr/local/bin .. 

another question is when using this tools, i need RTL SDR device or modem or just internet connection ? thanks...

**Comment by 0x454447415244** [comment]
You need an SS7 connection (SIGTRAN) from a telecom provider.

**Comment by HaxorGaruda** [comment]
is the meaning i connect internet from modem is use GSM..

**Comment by 0xc0decafe** [comment]
What you would need to run this tool is a M3UA connection, running over SCTP, running over IP. So yes,  you can run this tool with your modem internet connection, given you have the right STP to hook you up with the SS7 network.

cheers
