### ISSUE TITLE
ask again about config file

### ISSUE THREAD

**Issue by HaxorGaruda** [ernw/ss7MAPer#12]
sorry friend ..  i ask again....  hehe   :v: 

everything is ok, but when i run : application:start(ss7MAPer).
It's error about config file, then i copy config.example to config ..   but got this error ? 

`2> application:start(ss7MAPer).
SCTP Reconnect {127,0,0,1}:2905
SCTP Error {sctp_assoc_change,cant_assoc,0,0,0,0}, reconnecting
SCTP Reconnect {127,0,0,1}:2905
SCTP Error {sctp_assoc_change,cant_assoc,0,0,0,0}, reconnecting
SCTP Reconnect {127,0,0,1}:2905
SCTP Error {sctp_assoc_change,cant_assoc,0,0,0,0}, reconnecting
SCTP Reconnect {127,0,0,1}:2905
SCTP Error {sctp_assoc_change,cant_assoc,0,0,0,0}, reconnecting
`
my question is, would i must make new config file or use config.example default file ? thanks ...

**Comment by 0xc0decafe** [comment]
Hi,

you should change the remote ip addresses in the config file, to point to the STP you are using to connect to the SS7 network and the local ip to the local address you are using to reach the STP.

With the default config the tool tries to connect to localhost and unless you are running an STP on the local host, this wont work..

cheers
