### ISSUE TITLE
i build file but get error, Admin help me.... Thanks You

### ISSUE THREAD

**Issue by vequeemnhe** [ernw/ss7MAPer#13]
osmo_ss7 (compile)
*** ERROR in parse_transform function:
*** Reason     = function_clause
*** Location: {exprecs,403}
***       type = function
***    context = {context,sccp_codec,undefined,undefined}
***        acc = {pass1,
                     [global_title,sccp_addr,sccp_msg],
                     false,
                     [{sccp_addr,
                          [{record_field,182,{atom,182,res_nat_use}},
                           {record_field,183,{atom,183,route_on_ssn}},
                           {record_field,184,{atom,184,point_code}},
                           {record_field,185,{atom,185,ssn}},
                           {record_field,186,{atom,186,global_title}}]},
                      {global_title,
                          [{typed_record_field,
                               {record_field,173,{atom,173,gti}},
                               {type,173,range,
                                   [{integer,173,0},{integer,173,15}]}},
                           {typed_record_field,
                               {record_field,174,
                                   {atom,174,nature_of_addr_ind}},
                               {type,174,range,
                                   [{integer,174,0},{integer,174,127}]}},
                           {record_field,175,{atom,175,trans_type}},
                           {typed_record_field,
                               {record_field,176,{atom,176,encoding}},
                               {type,176,range,
                                   [{integer,176,0},{integer,176,15}]}},
                           {typed_record_field,
                               {record_field,177,{atom,177,numbering_plan}},
                               {type,177,range,
                                   [{integer,177,0},{integer,177,15}]}},
                           {record_field,178,{atom,178,phone_number}}]},
                      {sccp_msg,
                          [{typed_record_field,
                               {record_field,167,{atom,167,msg_type}},
                               {user_type,167,sccp_msg_type,[]}},
                           {record_field,168,{atom,168,parameters}}]}]}
***       form = {function,48,binarify,1,
                     [{clause,48,
                          [{var,48,'In'}],
                          [[{call,48,{atom,48,is_binary},[{var,48,'In'}]}]],
                          [{var,49,'In'}]},
                      {clause,50,
                          [{var,50,'In'}],
                          [[{call,50,{atom,50,is_list},[{var,50,'In'}]}]],
                          [{call,51,
                               {atom,51,list_to_binary},
                               [{var,51,'In'}]}]}]}
/root/Desktop/Hacking/HackMobile/ss7MAPer/deps/osmo_ss7/src/sccp_codec.erl:48: function_clause
Compiling /root/Desktop/Hacking/HackMobile/ss7MAPer/deps/osmo_ss7/src/sccp_codec.erl failed:
ERROR: compile failed while processing /root/Desktop/Hacking/HackMobile/ss7MAPer/deps/osmo_ss7: rebar_abort

i install it on Kali Linux roll pentest ..... help me

**Comment by Goyalexpo** [comment]
dear sir , 
I am having the same problem as mentioned above . And i have also tried to build it on windows .
But when i run ".\bin\ss7MAPer console " it starts and then stops automatically by creating erl_dump_crash file .
I think i am missing some dependency files .
Any help will be appreciated.

**Comment by 0xc0decafe** [comment]
Hi,

please give me at least:

- the os + version you are trying to build on
- the erlang version 'erl +v'
- stack traces (best attached as a file)
- crash dumps

cheers

/daniel

**Comment by Goyalexpo** [comment]
hello sir,
_**On windows 10**_ , i installed erlang 17.5 and installed binary release of ss7MAPer.
but when i start ss7MAPer from command prompt with admin by typing 
" C:\ss7MAPer\bin\ss7MAPer console"
it shows something and then ends up with erl_crash.dump file in installed directory of ss7MAPer .
The erl_crash.dump file is below -

[erl_crash.txt](https://github.com/ernw/ss7MAPer/files/732789/erl_crash.txt)

 i don't have any idea why is it happening..? And what i also need a guide on how to use it ,because there is nowhere a clear explanation of it .
Should i be connected to internet , when i use it.

**Comment by Goyalexpo** [comment]
Please reply sir i have been waiting for a long time
I have mentioned my problem in github

**Comment by y0d4a** [comment]
i got in same problem like vequeemnhe.
I use latest kali ver.
Erlang/OTP 19 [erts-8.2.1] 

strace:

> clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f1f9b4a99d0) = 3470
wait4(-1, ==> pkt (compile)
==> epcap (compile)
Compiling /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/epcap/c_src/epcap.c
In file included from /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/epcap/c_src/epcap.c:34:0:
c_src/epcap.h:42:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
ERROR: compile failed while processing /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/epcap: rebar_abort
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 3470
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3470, si_uid=0, si_status=1, si_utime=48, si_stime=14} ---
rt_sigreturn({mask=[]})                 = 3470
write(2, "+ ", 2+ )                       = 2
write(2, "cd", 2cd)                       = 2
write(2, " rel/", 5 rel/)                    = 5
write(2, "\n", 1
)                       = 1
chdir("/home/star/Downloads/ss7MAPer-master/ss7MAPer/rel") = 0
write(2, "+ ", 2+ )                       = 2
write(2, "rebar", 5rebar)                    = 5
write(2, " create-node", 12 create-node)            = 12
write(2, " nodeid=ss7MAPer", 16 nodeid=ss7MAPer)        = 16
write(2, "\n", 1
)                       = 1
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f1f9b4a99d0) = 3496
wait4(-1, ==> rel (create-node)
ERROR: One or more files already exist on disk and were not generated:
	* "reltool.config"
	* "files/erl"
	* "files/nodetool"
	* "files/ss7MAPer"
	* "files/sys.config"
	* "files/vm.args"
	* "files/ss7MAPer.cmd"
	* "files/start_erl.cmd"
	* "files/install_upgrade.escript"
To force overwriting, specify -f/--force/force=1 on the command line.
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3496
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3496, si_uid=0, si_status=0, si_utime=46, si_stime=19} ---
rt_sigreturn({mask=[]})                 = 3496
write(2, "+ ", 2+ )                       = 2
write(2, "cd", 2cd)                       = 2
write(2, " ..", 3 ..)                      = 3
write(2, "\n", 1
)                       = 1
chdir("/home/star/Downloads/ss7MAPer-master/ss7MAPer") = 0
write(2, "+ ", 2+ )                       = 2
write(2, "rebar", 5rebar)                    = 5
write(2, " generate", 9 generate)                = 9
write(2, "\n", 1
)                       = 1
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f1f9b4a99d0) = 3520
wait4(-1, ==> rel (generate)
ERROR: Unable to generate spec: read file info /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel/../../osmo_ss7/osmo_ss7 failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel: rebar_abort
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 3520
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3520, si_uid=0, si_status=1, si_utime=164, si_stime=47} ---
rt_sigreturn({mask=[]})                 = 3520
read(10, "", 8192)                      = 0
exit_group(1)                           = ?
+++ exited with 1 +++

>

**Comment by Goyalexpo** [comment]
Hello y04da,
I also faced this problem in kali linux but solved it bysearching on google.
You are missing pcap header. You need to install it using the deafault repositry of kali linux.
Type 

**_sudo apt-get install libpcap0.8-dev_** and your problem will be solved

**Comment by y0d4a** [comment]
tnx. Goyalexpo, pass that part, now got new issue:

> /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/sctp_core.erl:36: Warning: undefined callback function handle_sync_event/4 (behaviour 'gen_fsm')
Compiled src/sctp_core.erl
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/include/osmo_ss7.hrl:16: type record(_) undefined
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function code_change/3 (behaviour 'gen_server')
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function handle_call/3 (behaviour 'gen_server')
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function handle_info/2 (behaviour 'gen_server')
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function terminate/2 (behaviour 'gen_server')
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:83: Warning: variable 'Args' is unused
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:121: Warning: function terminate/2 is unused
/home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:125: Warning: function tx_sccp_udt/1 is unused
Compiling /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl failed:
ERROR: compile failed while processing /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7: rebar_abort
+ cd rel/
+ rebar create-node nodeid=ss7MAPer
==> rel (create-node)
ERROR: One or more files already exist on disk and were not generated:
	* "reltool.config"
	* "files/erl"
	* "files/nodetool"
	* "files/ss7MAPer"
	* "files/sys.config"
	* "files/vm.args"
	* "files/ss7MAPer.cmd"
	* "files/start_erl.cmd"
	* "files/install_upgrade.escript"
To force overwriting, specify -f/--force/force=1 on the command line.
+ cd ..
+ rebar generate
==> rel (generate)
ERROR: Unable to generate spec: read file info /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel/../../osmo_ss7/osmo_ss7 failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel: rebar_abort

>

**Comment by Goyalexpo** [comment]
hello y04da,
I think erlang is not completely installed on you os..
Tell me how did you install erlang  - by source code or default repositry of kali linux
And there is another tool in kali linux named as sctpscan
Use can use it to perform sctp attack on a machine

**Comment by y0d4a** [comment]
hello Goyalexpo, i reinstalled and now got new one :)

`Compiling /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl failed:
ERROR: compile failed while processing /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7: rebar_abort
+ cd rel/
+ rebar create-node nodeid=ss7MAPer
==> rel (create-node)
ERROR: One or more files already exist on disk and were not generated:
	* "reltool.config"
	* "files/erl"
	* "files/nodetool"
	* "files/ss7MAPer"
	* "files/sys.config"
	* "files/vm.args"
	* "files/ss7MAPer.cmd"
	* "files/start_erl.cmd"
	* "files/install_upgrade.escript"
To force overwriting, specify -f/--force/force=1 on the command line.
+ cd ..
+ rebar generate
==> rel (generate)
ERROR: Unable to generate spec: read file info /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel/../../osmo_sccp/deps/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP/TCAP failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /home/star/Downloads/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel: rebar_abort
`

maybe i need something like make clean and try again? :)

i installed erlang by default, from kali.

**Comment by 0xc0decafe** [comment]
> hello sir,
> On windows 10 , i installed erlang 17.5 and installed binary release of ss7MAPer.
> but when i start ss7MAPer from command prompt with admin by typing
> " C:\ss7MAPer\bin\ss7MAPer console"
> it shows something and then ends up with erl_crash.dump file in installed directory of ss7MAPer .
> The erl_crash.dump file is below -
> 
> erl_crash.txt
> 
> i don't have any idea why is it happening..? And what i also need a guide on how to use it ,because there is nowhere a clear explanation of it .
> Should i be connected to internet , when i use it.


from your crash dump:
`({application_start_failure,ss7MAPer,{{shutdown,{failed_to_start_child,ss7MAPer,{{badmatch,error,eprotonosupport}}`

you dont have an sctp driver installed on your windows machine.

cheers

**Comment by vequeemnhe** [comment]
Thanks you.... i have try but not work...
Kali linux 2 rolling...

**Comment by xiaoxie1979** [comment]
===> Verifying dependencies...
===> Compiling osmo_ss7
*** ERROR in parse_transform function:
*** Reason     = function_clause
*** Location: {exprecs,403}
***       type = function
***    context = {context,sccp_codec,undefined,undefined}
***        acc = {pass1,
                     [global_title,sccp_addr,sccp_msg],
                     false,
                     [{sccp_addr,
                          [{record_field,182,{atom,182,res_nat_use}},
                           {record_field,183,{atom,183,route_on_ssn}},
                           {record_field,184,{atom,184,point_code}},
                           {record_field,185,{atom,185,ssn}},
                           {record_field,186,{atom,186,global_title}}]},
                      {global_title,
                          [{typed_record_field,
                               {record_field,173,{atom,173,gti}},
                               {type,173,range,
                                   [{integer,173,0},{integer,173,15}]}},
                           {typed_record_field,
                               {record_field,174,
                                   {atom,174,nature_of_addr_ind}},
                               {type,174,range,
                                   [{integer,174,0},{integer,174,127}]}},
                           {record_field,175,{atom,175,trans_type}},
                           {typed_record_field,
                               {record_field,176,{atom,176,encoding}},
                               {type,176,range,
                                   [{integer,176,0},{integer,176,15}]}},
                           {typed_record_field,
                               {record_field,177,{atom,177,numbering_plan}},
                               {type,177,range,
                                   [{integer,177,0},{integer,177,15}]}},
                           {record_field,178,{atom,178,phone_number}}]},
                      {sccp_msg,
                          [{typed_record_field,
                               {record_field,167,{atom,167,msg_type}},
                               {user_type,167,sccp_msg_type,[]}},
                           {record_field,168,{atom,168,parameters}}]}]}
***       form = {function,48,binarify,1,
                     [{clause,48,
                          [{var,48,'In'}],
                          [[{call,48,{atom,48,is_binary},[{var,48,'In'}]}]],
                          [{var,49,'In'}]},
                      {clause,50,
                          [{var,50,'In'}],
                          [[{call,50,{atom,50,is_list},[{var,50,'In'}]}]],
                          [{call,51,
                               {atom,51,list_to_binary},
                               [{var,51,'In'}]}]}]}
===> Compiling _build/default/lib/osmo_ss7/src/sccp_codec.erl failed
_build/default/lib/osmo_ss7/src/sccp_codec.erl:48: function_clause
same question Does anyone know how to solve it? The version change problem still exists
