### ISSUE TITLE
Witch Hardwares do I need???

### ISSUE THREAD

**Issue by qwuedhiaujsodis** [ernw/ss7MAPer#14]
Hello guys,

I'm new in BTS attacks, I need to know witch HARDWARES do I need to build and run ss7MAPer?

**Comment by 0xc0decafe** [comment]
it runs on any linux system and needs an ethernet connection to your STP.

cheers

/daniel

**Comment by qwuedhiaujsodis** [comment]
Does it work with gsm modems?
If it does, what features should it have?

**Comment by 0xc0decafe** [comment]
No. You will need an M3UA link to the SS7 world.

**Comment by juba12** [comment]
Hi, can you be more specific, are you meaning a signaling gateway ? Which model/reference is accessible for example and do you need subscription ? Thank you in advance

**Comment by 0xc0decafe** [comment]
ok so to get you up and running you would need:

- SIGTRAN access to the SS7 network
  - get this from your local telecommunications distributor
- a global title to use on the SS7 network
  - to get one of these you must be a telco yourself, or again rent one
from your local telecommunications distributor
- the ss7MAPer software
- if you want to run ss7MAPer on windows you would need an SCTP driver
for windows.

Also, this does not belong here, as the title asks about hardware.
