### ISSUE TITLE
Please Help me 

### ISSUE THREAD

**Issue by getaw** [ernw/ss7MAPer#15]
How to fix 
ERROR: Unable to generate spec: read file info /home/getaw/ss7MAPer/deps/signerl/TCAP/ebin/tcap_tsm_fsm.beam failed

**Comment by 0xc0decafe** [comment]
System? erlang version?

**Comment by SumitRajput** [comment]
All set only one error : rebar shell not opening 
error : - Command 'shell' not understood or not applicable
  is there any way ??

**Comment by 0xc0decafe** [comment]
does not seem to be important anymore... closed. Please reopen on resurrection (;
