### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mohsinshaharyar** [ernw/ss7MAPer#16]
Hey Sir does it runs on windows? If not then how to I run it on linux?

**Comment by 0xc0decafe** [comment]
Yes, it does run on windows, otherwise why would there be a windows binary.

One problem with windows is, that Microsoft does not ship a SCTP driver, so you would have to find your own one.

cheers

/daniel

**Comment by mohsinshaharyar** [comment]
And does it intercepts the messages of the subscriber

**Comment by 0xc0decafe** [comment]
What exactly do you mean with 'And does it intercepts the messages of the subscriber' ?

**Comment by mohsinshaharyar** [comment]
Is this the Hack of the ss7 to attack the target?

**Comment by 0xc0decafe** [comment]
No.

**Comment by 246642** [comment]
how do i get start this github

**Comment by 0xc0decafe** [comment]
not sure why you want to start github. please clarify.

**Comment by 246642** [comment]
Just want to be a programme

**Comment by 0xc0decafe** [comment]
You can be a program, i believe in you!

**Comment by 246642** [comment]
Thanks dear
