### ISSUE TITLE
config error 

### ISSUE THREAD

**Issue by Nabilfaidi** [ernw/ss7MAPer#18]
HI
i build ss7MAPer but when i try to start it i got this error.
2> application:start(ss7MAPer).
Error reading config file [["./config"]]:
eisdir
{error,{{shutdown,{failed_to_start_child,ss7MAPer,
                                         config_error}},
        {ss7MAPer_app,start,[normal,["./config"]]}}}

any help thanks in advance

**Comment by 0xc0decafe** [comment]
Do you have a configuration file './config' ?

**Comment by Nabilfaidi** [comment]
Hi thx for your reply
yes i create a config directory and move edited config.example file under it.
thanks in advance

**Comment by 0xc0decafe** [comment]
That might be the problem, as there is no such thing as a config directory. just throw it in your current working directory and name it config.

cheers

**Comment by Nabilfaidi** [comment]
thank you  @0xc0decafe is working now
