### ISSUE TITLE
Error .. Help me

### ISSUE THREAD

**Issue by handsmcute** [ernw/ss7MAPer#21]
Compiling /root/Documents/ss7MAPer/deps/epcap/c_src/epcap.c
/root/Documents/ss7MAPer/deps/epcap/c_src/epcap.c:32:16: fatal error: ei.h: No such file or directory
 #include <ei.h>
                ^
compilation terminated.
ERROR: compile failed while processing /root/Documents/ss7MAPer/deps/epcap: rebar_abort

**Comment by 0xc0decafe** [comment]
see #8
