### ISSUE TITLE
osmo_ss7

### ISSUE THREAD

**Issue by Anknownguy** [ernw/ss7MAPer#22]
root@root:~/ss7MAPer# rebar co
==> pkt (compile)
==> epcap (compile)
Compiling c_src/epcap.c
Compiling c_src/epcap_priv.c
==> rel (compile)
==> osmo_ss7 (compile)
/root/ss7MAPer/deps/osmo_ss7/src/sctp_core.erl:36: Warning: undefined callback function handle_sync_event/4 (behaviour 'gen_fsm')
Compiled src/sctp_core.erl
Compiled src/exprecs.erl
Compiled src/xua_asp_fsm.erl
Compiled src/xua_asp_test.erl
/root/ss7MAPer/deps/osmo_ss7/src/xua_codec.erl:42: Warning: variable 'RemainLen' is unused
/root/ss7MAPer/deps/osmo_ss7/src/xua_codec.erl:42: Warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)
Compiled src/xua_codec.erl
/root/ss7MAPer/deps/osmo_ss7/src/xua_as_fsm.erl:82: Warning: variable 'From' is unused
/root/ss7MAPer/deps/osmo_ss7/src/xua_as_fsm.erl:149: Warning: variable 'Params' is unused
Compiled src/xua_as_fsm.erl
/root/ss7MAPer/deps/osmo_ss7/src/sua_asp.erl:54: Warning: variable 'LoopDat' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sua_asp.erl:57: Warning: variable 'LoopDat' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sua_asp.erl:61: Warning: variable 'LoopDat' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sua_asp.erl:64: Warning: variable 'LoopDat' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sua_asp.erl:68: Warning: variable 'LoopDat' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sua_asp.erl:71: Warning: variable 'LoopDat' is unused
Compiled src/sua_asp.erl
Compiled src/sua_sccp_conv.erl
/root/ss7MAPer/deps/osmo_ss7/src/ss7_service_dump.erl:36: Warning: undefined callback function code_change/4 (behaviour 'gen_fsm')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_service_dump.erl:36: Warning: undefined callback function handle_event/3 (behaviour 'gen_fsm')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_service_dump.erl:36: Warning: undefined callback function handle_info/3 (behaviour 'gen_fsm')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_service_dump.erl:36: Warning: undefined callback function handle_sync_event/4 (behaviour 'gen_fsm')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_service_dump.erl:36: Warning: undefined callback function terminate/3 (behaviour 'gen_fsm')
Compiled src/ss7_service_dump.erl
Compiled src/ss7_routes.erl
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m2ua.erl:36: Warning: undefined callback function code_change/3 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m2ua.erl:36: Warning: undefined callback function handle_call/3 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m2ua.erl:36: Warning: undefined callback function handle_cast/2 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m2ua.erl:108: Warning: function tx_sccp_udt/1 is unused
Compiled src/ss7_link_m2ua.erl
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function code_change/3 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function handle_call/3 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:36: Warning: undefined callback function handle_info/2 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:94: Warning: variable 'Args' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:131: Warning: variable 'P' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:135: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_m3ua.erl:139: Warning: function tx_sccp_udt/1 is unused
Compiled src/ss7_link_m3ua.erl
/root/ss7MAPer/deps/osmo_ss7/src/sg_asp_sup.erl:40: Warning: variable 'AsSupPid' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sg_asp_sup.erl:40: Warning: variable 'Name' is unused
Compiled src/sg_asp_sup.erl
Compiled src/sg_as_sup.erl
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:61: Warning: opaque type tid() is not exported
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:358: Warning: variable 'FromPid' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:385: Warning: variable 'FromPid' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:390: Warning: variable 'FromPid' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:402: Warning: variable 'FromPid' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:425: Warning: variable 'FromPid' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_links.erl:442: Warning: variable 'LinksetTbl' is unused
Compiled src/ss7_links.erl
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_ipa_client.erl:36: Warning: undefined callback function code_change/3 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_ipa_client.erl:36: Warning: undefined callback function handle_call/3 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_ipa_client.erl:36: Warning: undefined callback function terminate/2 (behaviour 'gen_server')
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_ipa_client.erl:78: Warning: variable 'LocalIp' is unused
/root/ss7MAPer/deps/osmo_ss7/src/ss7_link_ipa_client.erl:78: Warning: variable 'LocalPort' is unused
Compiled src/ss7_link_ipa_client.erl
/root/ss7MAPer/deps/osmo_ss7/src/sctp_sua.erl:36: Warning: undefined callback function handle_sync_event/4 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_sua.erl:36: Warning: undefined callback function state_change/2 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_sua.erl:80: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_sua.erl:84: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_sua.erl:88: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_sua.erl:156: Warning: variable 'LoopDat' is unused
Compiled src/sctp_sua.erl
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:22: Warning: undefined callback function handle_sync_event/4 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:22: Warning: undefined callback function state_change/2 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:72: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:77: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:80: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:87: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:97: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:138: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:145: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:153: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:160: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:167: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:207: Warning: variable 'M2ua' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:208: Warning: variable 'State' is unused
Compiled src/sctp_m2ua.erl
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2pa.erl:36: Warning: undefined callback function handle_sync_event/4 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2pa.erl:36: Warning: undefined callback function state_change/2 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2pa.erl:95: Warning: variable 'State' is unused
Compiled src/sctp_m2pa.erl
*** ERROR in parse_transform function:
*** Reason     = function_clause
*** Location: {exprecs,403}
***       type = function
***    context = {context,osmo_util,undefined,undefined}
***        acc = {pass1,
                     [primitive],
                     false,
                     [{pointcode,
                          [{typed_record_field,
                               {record_field,15,{atom,15,repr}},
                               {user_type,15,pointcode_repr,[]}},
                           {record_field,16,{atom,16,value}}]},
                      {primitive,
                          [{record_field,6,{atom,6,subsystem}},
                           {record_field,7,{atom,7,gen_name}},
                           {typed_record_field,
                               {record_field,8,{atom,8,spec_name}},
                               {user_type,8,prim_spec_name,[]}},
                           {record_field,9,{atom,9,parameters}}]}]}
***       form = {function,51,digit_list2int,2,
                     [{clause,51,
                          [{var,51,'Int'},{nil,51}],
                          [],
                          [{var,52,'Int'}]},
                      {clause,53,
                          [{var,53,'Int'},
                           {cons,53,{var,53,'Digit'},{var,53,'Tail'}}],
                          [],
                          [{call,54,
                               {atom,54,digit_list2int},
                               [{op,54,'+',
                                    {op,54,'*',{var,54,'Int'},{integer,54,10}},
                                    {var,54,'Digit'}},
                                {var,54,'Tail'}]}]}]}
*** ERROR in parse_transform function:
*** Reason     = function_clause
*** Location: {exprecs,403}
***       type = function
***    context = {context,sccp_codec,undefined,undefined}
***        acc = {pass1,
                     [global_title,sccp_addr,sccp_msg],
                     false,
                     [{sccp_addr,
                          [{record_field,182,{atom,182,res_nat_use}},
                           {record_field,183,{atom,183,route_on_ssn}},
                           {record_field,184,{atom,184,point_code}},
                           {record_field,185,{atom,185,ssn}},
                           {record_field,186,{atom,186,global_title}}]},
                      {global_title,
                          [{typed_record_field,
                               {record_field,173,{atom,173,gti}},
                               {type,173,range,
                                   [{integer,173,0},{integer,173,15}]}},
                           {typed_record_field,
                               {record_field,174,
                                   {atom,174,nature_of_addr_ind}},
                               {type,174,range,
                                   [{integer,174,0},{integer,174,127}]}},
                           {record_field,175,{atom,175,trans_type}},
                           {typed_record_field,
                               {record_field,176,{atom,176,encoding}},
                               {type,176,range,
                                   [{integer,176,0},{integer,176,15}]}},
                           {typed_record_field,
                               {record_field,177,{atom,177,numbering_plan}},
                               {type,177,range,
                                   [{integer,177,0},{integer,177,15}]}},
                           {record_field,178,{atom,178,phone_number}}]},
                      {sccp_msg,
                          [{typed_record_field,
                               {record_field,167,{atom,167,msg_type}},
                               {user_type,167,sccp_msg_type,[]}},
                           {record_field,168,{atom,168,parameters}}]}]}
***       form = {function,48,binarify,1,
                     [{clause,48,
                          [{var,48,'In'}],
                          [[{call,48,{atom,48,is_binary},[{var,48,'In'}]}]],
                          [{var,49,'In'}]},
                      {clause,50,
                          [{var,50,'In'}],
                          [[{call,50,{atom,50,is_list},[{var,50,'In'}]}]],
                          [{call,51,
                               {atom,51,list_to_binary},
                               [{var,51,'In'}]}]}]}
/root/ss7MAPer/deps/osmo_ss7/src/osmo_ss7_sup.erl:45: Warning: variable 'Args' is unused
/root/ss7MAPer/deps/osmo_ss7/src/osmo_ss7_sup.erl:54: Warning: variable 'Local' is unused
/root/ss7MAPer/deps/osmo_ss7/src/osmo_ss7_sup.erl:54: Warning: variable 'Remote' is unused
/root/ss7MAPer/deps/osmo_ss7/src/osmo_ss7_sup.erl:60: Warning: variable 'Local' is unused
/root/ss7MAPer/deps/osmo_ss7/src/osmo_ss7_sup.erl:60: Warning: variable 'Remote' is unused
Compiled src/osmo_ss7_sup.erl
/root/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl:51: function_clause
Compiling /root/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl failed:
ERROR: compile failed while processing /root/ss7MAPer/deps/osmo_ss7: rebar_abort

**Comment by 0xc0decafe** [comment]
As long as you keep posting error messages without any 'Hi', or other forms of interpersonal communication, I'll keep closing tickets.

 kthxbye

**Comment by Anknownguy** [comment]
sorry bro,
i'm using windows 10 and i'm using ss7maper user windows linux bash shell.. i fixed the pcap.h error while compiling but now i'm stuck at this new error.
i'm sorry i posted the error without interpersonal communication..

**Comment by 0xc0decafe** [comment]
I would suggest you try the windows binary. Although there is no open (read free of charge) sctp driver for windows, so it wount be of much use.

cheers
