### ISSUE TITLE
rebar not compiling 

### ISSUE THREAD

**Issue by mohnqwerty** [ernw/ss7MAPer#23]
ss7MAPer (compile)
src/ss7MAPer.erl:83: field asp_id undefined in record sigtran_link
src/ss7MAPer.erl:84: field net_app undefined in record sigtran_link
src/ss7MAPer.erl:84: field route_ctx undefined in record sigtran_link
src/ss7MAPer.erl:79: Warning: variable 'Asp_ID' is unused
src/ss7MAPer.erl:80: Warning: variable 'Route_CTX' is unused
src/ss7MAPer.erl:81: Warning: variable 'Net_Appearance' is unused
Compiling src/ss7MAPer.erl failed:
ERROR: compile failed while processing /root/ss7MAPer: rebar_abort

**Comment by 0xc0decafe** [comment]
As long as you keep posting error messages without any 'Hi', or other forms of interpersonal communication, I'll keep closing tickets.

kthxbye

**Comment by mohnqwerty** [comment]
hi 
i am unable to compile rebar 
after typing this 'rebar co' i get this error 
ss7MAPer (compile)
src/ss7MAPer.erl:83: field asp_id undefined in record sigtran_link
src/ss7MAPer.erl:84: field net_app undefined in record sigtran_link
src/ss7MAPer.erl:84: field route_ctx undefined in record sigtran_link
src/ss7MAPer.erl:79: Warning: variable 'Asp_ID' is unused
src/ss7MAPer.erl:80: Warning: variable 'Route_CTX' is unused
src/ss7MAPer.erl:81: Warning: variable 'Net_Appearance' is unused
Compiling src/ss7MAPer.erl failed:
ERROR: compile failed while processing /root/ss7MAPer: rebar_abort

**Comment by 0xc0decafe** [comment]
OS, erl version?
