### ISSUE TITLE
prepare_n_build.sh error while executing

### ISSUE THREAD

**Issue by Mj13185** [ernw/ss7MAPer#24]
root@kali:~/ss7MAPer# ./prepare_n_build.sh 
+ git clone https://github.com/ernw/ss7MAPer
fatal: destination path 'ss7MAPer' already exists and is not an empty directory.
+ cd ss7MAPer
+ rebar get-deps
==> rel (get-deps)
==> ss7MAPer (get-deps)
Pulling osmo_ss7 from {git,"git://git.osmocom.org/erlang/osmo_ss7/","master"}
Cloning into 'osmo_ss7'...
Pulling osmo_sccp from {git,"git://git.osmocom.org/erlang/osmo_sccp/",
                            "master"}
Cloning into 'osmo_sccp'...
Pulling osmo_map from {git,"git://git.osmocom.org/erlang/osmo_map/","master"}
Cloning into 'osmo_map'...
==> rel (get-deps)
==> osmo_ss7 (get-deps)
Pulling epcap from {git,"git://git.osmocom.org/erlang/epcap","master"}
Cloning into 'epcap'...
==> epcap (get-deps)
Pulling pkt from {git,"git://github.com/msantos/pkt.git","master"}
Cloning into 'pkt'...
==> pkt (get-deps)
==> osmo_sccp (get-deps)
==> osmo_map (get-deps)
+ cd deps/osmo_map
+ patch -p1
patching file asn1/MAP-Contracts.asn
patching file ebin/osmo_map.app
patching file rebar.config
patching file src/map_dlg_server.erl
patching file src/map_helper.erl
patching file src/map_ss_server.erl
+ cd ../osmo_sccp
+ patch -p1
patching file ebin/osmo_sccp.app
patching file rebar.config
patching file src/osmo_sccp_tcap.erl
patching file src/sccp_scrc.erl
patching file src/sccp_user.erl
+ cd ../osmo_ss7
+ patch -p1
patching file include/osmo_ss7.hrl
patching file include/sccp.hrl
patching file src/m3ua_codec.erl
patching file src/m3ua_core.erl
patching file src/sccp_codec.erl
patching file src/sctp_core.erl
patching file src/ss7_link_m3ua.erl
patching file src/ss7_links.erl
patching file src/ss7_routes.erl
+ cd ../../
+ sed -i s/DRV_CFLAGS/CFLAGS/g deps/epcap/rebar.config
+ sed -i s/DRV_LDFLAGS/LDFLAGS/g deps/epcap/rebar.config
+ cd deps
+ git clone http://cgit.osmocom.org/erlang/signerl/
Cloning into 'signerl'...
+ cd signerl/TCAP/asn_src/ITU
+ make
erlc  -W -b ber_bin +optimize +debug_info Remote-Operations-Information-Objects.asn Remote-Operations-Generic-ROS-PDUs.asn Remote-Operations-Useful-Definitions.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc  -W -b ber_bin +optimize +debug_info TCAPMessages.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc  -W -b ber_bin +optimize +debug_info TR.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu TR.erl
TR.erl:662: Warning: variable 'Arg' is unused
erlc  -W -b ber_bin +optimize +debug_info TC.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu TC.erl
TC.erl:886: Warning: variable 'Arg' is unused
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu TCAPMessages.erl
TCAPMessages.erl:490: Warning: variable 'Arg' is unused
erlc  -W -b ber_bin +optimize +debug_info DialoguePDUs.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu DialoguePDUs.erl
DialoguePDUs.erl:1001: Warning: variable 'Arg' is unused
erlc  -W -b ber_bin +optimize +debug_info UnidialoguePDUs.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu UnidialoguePDUs.erl
UnidialoguePDUs.erl:396: Warning: variable 'Arg' is unused
erlc  -W -b ber_bin +optimize +debug_info TC-TMP.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc  -W -b ber_bin +optimize +debug_info TC-Testing-User.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu TC-Testing-User.erl
TC-Testing-User.erl:278: Warning: variable 'Arg' is unused
erlc  -W -b ber_bin +optimize +debug_info TCAP-Examples.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu TCAP-Examples.erl
TCAP-Examples.erl:523: Warning: variable 'Arg' is unused
erlc  -W -b ber_bin +optimize +debug_info TCAP-Tools.asn
Warning: The option 'ber_bin' is now called 'ber'.
Warning: The option 'optimize' is no longer needed.
erlc -b beam -W -v +warn_unused_vars +debug_info -o ../../ebin/itu TCAP-Tools.erl
TCAP-Tools.erl:263: Warning: variable 'Arg' is unused
rm TC.erl
+ cd ../../../../..
+ cp deps/signerl/TCAP/asn_src/ITU/DialoguePDUs.erl deps/signerl/TCAP/asn_src/ITU/DialoguePDUs.hrl deps/signerl/TCAP/asn_src/ITU/Remote-Operations-Generic-ROS-PDUs.erl deps/signerl/TCAP/asn_src/ITU/Remote-Operations-Generic-ROS-PDUs.hrl deps/signerl/TCAP/asn_src/ITU/Remote-Operations-Information-Objects.erl deps/signerl/TCAP/asn_src/ITU/Remote-Operations-Useful-Definitions.erl deps/signerl/TCAP/asn_src/ITU/TC-TMP.erl deps/signerl/TCAP/asn_src/ITU/TC-TMP.hrl deps/signerl/TCAP/asn_src/ITU/TC-Testing-User.erl deps/signerl/TCAP/asn_src/ITU/TC-Testing-User.hrl deps/signerl/TCAP/asn_src/ITU/TC.hrl deps/signerl/TCAP/asn_src/ITU/TCAP-Examples.erl deps/signerl/TCAP/asn_src/ITU/TCAP-Examples.hrl deps/signerl/TCAP/asn_src/ITU/TCAP-Tools.erl deps/signerl/TCAP/asn_src/ITU/TCAPMessages.erl deps/signerl/TCAP/asn_src/ITU/TCAPMessages.hrl deps/signerl/TCAP/asn_src/ITU/TR.erl deps/signerl/TCAP/asn_src/ITU/TR.hrl deps/signerl/TCAP/asn_src/ITU/UnidialoguePDUs.erl deps/signerl/TCAP/asn_src/ITU/UnidialoguePDUs.hrl deps/osmo_sccp/src/
+ mkdir deps/epcap/deps
+ ln -sd ../../pkt deps/epcap/deps/pkt
+ mkdir deps/osmo_sccp/deps
+ ln -sd ../../osmo_ss7 deps/osmo_sccp/deps/osmo_ss7
+ ln -sd ../../epcap deps/osmo_sccp/deps/epcap
+ ln -sd ../../pkt deps/osmo_sccp/deps/pkt
+ ln -sd ../../signerl/MAP deps/osmo_sccp/deps/MAP
+ ln -sd ../../signerl/SCCP deps/osmo_sccp/deps/SCCP
+ ln -sd ../../signerl/TCAP deps/osmo_sccp/deps/TCAP
+ mkdir deps/osmo_map/deps
+ ln -sd ../../osmo_ss7 deps/osmo_map/deps/osmo_ss7
+ ln -sd ../../epcap deps/osmo_map/deps/epcap
+ ln -sd ../../pkt deps/osmo_map/deps/pkt
+ cp deps/signerl/SCCP/itu/include/sccp.hrl deps/osmo_sccp/src/
+ cp deps/signerl/TCAP/include/tcap.hrl deps/osmo_map/src/
+ rebar co
==> pkt (compile)
Compiled src/pkt_802_1q.erl
Compiled src/pkt_ether.erl
Compiled src/pkt_dlt.erl
Compiled src/pkt_ipproto.erl
Compiled src/pkt_mpls.erl
Compiled src/pkt_lldp.erl
Compiled src/pkt_ipv6_routing.erl
Compiled src/pkt_vrrp.erl
Compiled src/pkt_linux_cooked.erl
Compiled src/pkt_sctp.erl
Compiled src/pkt_ipv6_dstopts.erl
Compiled src/pkt_ipv6_fragment.erl
Compiled src/pkt_udp.erl
Compiled src/pkt_igmp.erl
Compiled src/pkt_null.erl
Compiled src/pkt_ipv4.erl
Compiled src/pkt_ipv6.erl
Compiled src/pkt.erl
Compiled src/pkt_icmp6.erl
Compiled src/pkt_ipv6_hopopts.erl
Compiled src/pkt_gre.erl
Compiled src/pkt_tcp.erl
Compiled src/pkt_arp.erl
Compiled src/pkt_llc.erl
Compiled src/pkt_ipv6_esp.erl
Compiled src/pkt_icmp.erl
Compiled src/pkt_ipv6_ah.erl
==> epcap (compile)
Compiled src/epcap.erl
Compiled src/epcap_net.erl
/root/ss7MAPer/ss7MAPer/deps/epcap/src/sniff.erl:56: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
/root/ss7MAPer/ss7MAPer/deps/epcap/src/sniff.erl:59: Warning: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/2
/root/ss7MAPer/ss7MAPer/deps/epcap/src/sniff.erl:66: Warning: gen_fsm:start/4 is deprecated and will be removed in a future release; use gen_statem:start/4
Compiled src/sniff.erl
Compiling /root/ss7MAPer/ss7MAPer/deps/epcap/c_src/epcap.c
In file included from /root/ss7MAPer/ss7MAPer/deps/epcap/c_src/epcap.c:34:0:
c_src/epcap.h:42:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
ERROR: compile failed while processing /root/ss7MAPer/ss7MAPer/deps/epcap: rebar_abort
+ cd rel/
+ rebar create-node nodeid=ss7MAPer
==> rel (create-node)
Writing files/erl
Writing files/nodetool
Writing files/ss7MAPer
Writing files/sys.config
Writing files/vm.args
Writing files/ss7MAPer.cmd
Writing files/start_erl.cmd
Writing files/install_upgrade.escript
ERROR: One or more files already exist on disk and were not generated:
	* "reltool.config"
To force overwriting, specify -f/--force/force=1 on the command line.
+ cd ..
+ rebar generate
==> rel (generate)
==> rel (generate)
ERROR: Unable to generate spec: read file info /root/ss7MAPer/ss7MAPer/deps/signerl/TCAP/ebin/tcap_tco_server.beam failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /root/ss7MAPer/ss7MAPer/rel: rebar_abort

**Comment by 0xc0decafe** [comment]
As long as you keep posting error messages without any 'Hi', or other forms of interpersonal communication, I'll keep closing tickets.

kthxbye

**Comment by Mj13185** [comment]
i am sorry.. Hiii...now please help me out

**Comment by 0xc0decafe** [comment]
fixed in bb8d6d55e145f81e6276687d11b0952842b99bda
