### ISSUE TITLE
erlang is crashing

### ISSUE THREAD

**Issue by Thuwarakan** [ernw/ss7MAPer#25]
=erl_crash_dump:0.3
Tue Oct 31 01:50:06 2017
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,ss7MAPer,{{shutdown,{failed_to_start_child,ss7MAPer,{{badmatch,{error,eprotonosupport}},[{m3ua_core,init,1,[{file,"src/m3ua
System version: Erlang/OTP 18 [erts-7.3] [64-bit] [smp:2:2] [async-threads:10]
Compiled: Mon Mar 14 21:51:02 2016
Taints: 
Atoms: 8191
Calling Thread: scheduler:1
=scheduler:1
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: THR_PRGR_LATER_OP
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK | NONEMPTY | UNKNOWN(134217728)
Current Process: <0.0.0>
Current Process State: Running
Current Process Internal State: ACT_PRIO_NORMAL | USR_PRIO_NORMAL | PRQ_PRIO_NORMAL | ACTIVE | RUNNING | TRAP_EXIT
Current Process Program counter: 0x00000000036c7b98 (init:sleep/1 + 64)
Current Process CP: 0x0000000000000000 (invalid)
Current Process Limited Stack Trace:
0x0000000002445168:SReturn addr 0x36C4D90 (init:loop/1 + 856)
0x0000000002445170:SReturn addr 0xE838CE98 (<terminate process normally>)
=scheduler:2
Scheduler Sleep Info Flags: SLEEPING | POLL_SLEEPING | WAITING
Scheduler Sleep Info Aux Work: 
Current Port: 
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 0
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: OUT_OF_WORK | HALFTIME_OUT_OF_WORK
Current Process: 
=memory
total: 11287040
processes: 3500104
processes_used: 3477744
system: 7786936
atom: 215345
atom_used: 212239
binary: 49104
code: 4961198
ets: 70504
![aaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/25005477/32193872-9f7fe386-bdde-11e7-81e9-0a6cbae37263.JPG)
[ss7MAPer.zip](https://github.com/ernw/ss7MAPer/files/1428646/ss7MAPer.zip)

**Comment by 0xc0decafe** [comment]
Hi,

as the error message tells:

> {error,eprotonosupport}

this is due to the fact that you are missing a SCTP driver for your windows system.

best
