### ISSUE TITLE
Compile failed and rebar aborted.

### ISSUE THREAD

**Issue by illegalblue** [ernw/ss7MAPer#26]
Kali linux:  The prepare_n_build.sh  shows lot of errors.

Also tried running commands manually. Used ./rebar instead of just rebar as it didnt work. 
Attached the screenshot too

![screenshot from 2017-12-03 03-11-09](https://user-images.githubusercontent.com/29424127/33519987-f3272f68-d7d7-11e7-8805-3f802b3f6a00.png)
![screenshot from 2017-12-03 03-12-03](https://user-images.githubusercontent.com/29424127/33519989-017d80e4-d7d8-11e7-8d3d-8c48449146ec.png)
![screenshot from 2017-12-03 03-12-20](https://user-images.githubusercontent.com/29424127/33519992-06339ed4-d7d8-11e7-899e-35c2fb87eefd.png)

**Comment by 0xc0decafe** [comment]
Hi,

apparently 'rebar' is not installed in $PATH, that's why prepare_n_build.sh is failing in the first screen.
cant say much about the other two, the full shell output would be useful.

The build process really sucks ass, so why don't you run one of the prebuild binaries?

cheers

/daniel
