### ISSUE TITLE
M3UA Link

### ISSUE THREAD

**Issue by Retsim** [ernw/ss7MAPer#28]
Hey,

Thanks for this peace of software, I'm trying to use it to check/experiment SS7.
I'm currently having this message after SCTP reconnect:

> SCTP Reconnect {1,2,3,4}:1234                                                                                                                                                                                 
> ss7_link_m3ua: SCTP_ESTABLISH.ind -> ASP_UP.req                                                                                                                                                                    
> SCRC Init PropList[{sup_pid,<0.68.0>},                                                                                                                                                                             
>                    {mtp_tx_action,                                                                                                                                                                                 
>                        {callback_fn,#Fun<ss7MAPer.0.6783143>,<0.72.0>}},                                                                                                                                           
>                    {ni,2}]

> Waiting for M3UA link ...                                                                                                                                                                                          
> Link not ready, sleeping...

I'm trying to understand this step:
Maybe there some communication failure causing this loop.
Like waiting for an answer from our SCTP server, without ever getting it.
Should we manually open the Client Port and route it to ss7MAPer ?

Also, are the sccp / target config need to be correct to allow the M3UA link step, or should we be able to get through this step with only sctp / m3ua settings in config ? (Even if later ones will be failing)

Finally, is there a way to enable or have more logs, to better understand steps.

Thanks !

**Comment by 0xc0decafe** [comment]
Hi,

at this step you are successfully connected to the SCTP server. now the upper layer, M3UA, kicks in and tries to establish its M3UA session.

`ss7_link_m3ua: SCTP_ESTABLISH.ind -> ASP_UP.req`

an ASP-UP request should be sent on SCTP and should be able to see it in a trace.
there is an open m3ua implementation that you can use for testing: https://sourceforge.net/projects/openss7gw

sccp and targets are not needed for m3ua. to get more debug, you would need a working build environment to get your own custom binaries, as the released binaries are heavily quieted. that would also allow you to use the erlang debugger.

best

/daniel

**Comment by silverhigh1** [comment]
thanks good read bro email me at leahcomer42@gmail.com i have some qustions i need your assistance with

**Comment by 0xc0decafe** [comment]
please open a new ticket for them.

cheers

**Comment by benseshi** [comment]
Dude can u please make a video of step by step process do anyone please

**Comment by silverhigh1** [comment]
brother can u add me on icq or a platform for messaging your on i am an
enthusiast and would love to build a friendship in this fascinating work

**Comment by silverhigh1** [comment]
720922345 my icq add
