### ISSUE TITLE
Ss7 

### ISSUE THREAD

**Issue by 2017n0856** [ernw/ss7MAPer#29]
Hi friends!
                 Actually I want to test ss7 method on my family mobiles and want to receive calls and sms for testing using ss7 method. But the problem is that I dont know much about ss7. 
Can someone plese tell me what are the requiremets(softwares and hardwares) for this purpose?
Secondly, I want to about an article. I read about ss7 mapper in this site. What is that? And what to do with that code? I cannot be able to understand how and where to use that code? Can someone guide me completely about this? Please someone help me and tell me the complete procedure in easy english step by step. Thanks

**Comment by 0xc0decafe** [comment]
Hi,

however you turn it, there will never be SS7 on your handset.
I'll keep this open if someone is interested in writing a SS7 beginners tutorial, i am not.

cheers

/daniel

**Comment by emx** [comment]
Do you need help typing on your keyboard too?

**Comment by takeshixx** [comment]
This is the wrong place for such questions. This issue tracker is for ss7MAPer, not about SS7 in general.
