### ISSUE TITLE
Command 'shell' not understood or not applicable

### ISSUE THREAD

**Issue by ghost** [ernw/ss7MAPer#3]
Hi. when i try to execute the rebar shell command, the program don't start. This is the output of command:

==> Entering directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_ss7'
==> Entering directory`/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/epcap'
==> Entering directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/pkt'
WARNING: deprecated port_envs option used
Option 'port_envs' has been deprecated
in favor of 'port_env'.
'port_envs' will be removed soon.

==> Leaving directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/pkt'
WARNING: deprecated port_envs option used
Option 'port_envs' has been deprecated
in favor of 'port_env'.
'port_envs' will be removed soon.

==> Leaving directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/epcap'
==> Entering directory`/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel'
==> Leaving directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_ss7/rel'
==> Leaving directory`/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_ss7'
==> Entering directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_sccp'
==> Leaving directory`/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_sccp'
==> Entering directory `/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_map'
==> Leaving directory`/root/Scrivania/SS7_HACKING/ss7MAPer-master/ss7MAPer/deps/osmo_map'
Command 'shell' not understood or not applicable

**Comment by MagicMuffins** [comment]
Hi quick question, but did you patch all of the dependencies correctly and make the links?

It looks like your problems pertain to this area....... try to run these again, from the ss7Mapper folder:

mkdir deps/osmo_sccp/deps  
ln -sd ../../osmo_ss7 deps/osmo_sccp/deps/osmo_ss7  
ln -sd ../../epcap deps/osmo_sccp/deps/epcap  
ln -sd ../../pkt deps/osmo_sccp/deps/pkt  
ln -sd ../../signerl/MAP deps/osmo_sccp/deps/MAP  
ln -sd ../../signerl/SCCP deps/osmo_sccp/deps/SCCP  
ln -sd ../../signerl/TCAP deps/osmo_sccp/deps/TCAP  
mkdir deps/osmo_map/deps  
ln -sd ../../osmo_ss7 deps/osmo_map/deps/osmo_ss7  
ln -sd ../../epcap deps/osmo_map/deps/epcap  
ln -sd ../../pkt deps/osmo_map/deps/pkt   

---

**Comment by gprms** [comment]
Hi. I have the same issue as Gabry770. At the last line appeared "Command 'shell' not understood or not applicable". I tried it in two different vm (Kali2 & Ubuntu14.04) but I got the same error. I have already patched all of the dependencies again but it doesn't seem to work.

**Comment by ghost** [comment]
Hi, i have try to patch dependencies again,  but it doesn't seem to work. 
Same problem, i'm on kali linux, there are other solutions?

**Comment by MagicMuffins** [comment]
Hmm.. Im sorry as I am not a developer for this type of stuff.. The OP seems to have disappeared off the face of the Earth, but with teamwork I am sure that we can find a solution. May I ask how you installed erlang and rebar? Did you use the links provided or use the terminal to obtain it? Did you get the deps to build? Did you patch the rebar.config? Did you fetch the dependencies in the correct folder and go to the right directory to build the ASN.1 files? I know the instructions are not clear and you need to use some guesswork and context clues as to when to change directories. I will not have access to my Linux machine (Kali bleeding edge) for a while and therefore cannot recreate this problem, but when I get the chance to, perhaps after school I will provide a detailed guide pertaining to the steps that I took to get this working, as well as look at this issue closer. Try to make sure that you also have the correct dependencies for your system as a whole.

Until next time.

**Comment by ghost** [comment]
i have obtained erlang and rebar from debian repository with apt-get command, the deps are ok, i have patched rebar.config. But i don't know, i have follow step to step the instructions.

**Comment by MagicMuffins** [comment]
Ok.. Your distro is kali? Try the kali repo to get erl and rebar, and if that doesnt work just get it from the site, and im pretty sure that I used rebar from git, get it from here https://github.com/rebar/rebar , but only get it from online if kali repos dont work.. The distro's repos are there because they provide the latest best working variant of software. The main point to add repos from other distros is to obtain software not obtainable in the current distro. This may seem like much, but the end result is worth it.

**Comment by 0xc0decafe** [comment]
Not dead, but away (;
I think you are using other versions of relang and/or rebar. im using 
- Erlang/OTP 18 [erts-7.3]
- rebar 2.6.1 18 20160820_080329

If the rebar shell command is not applicable, you can try 'erl -pa deps/*/ebin -pa ebin' which should do exactly the same.

Regarding the deps and patching, i know this is ugly and im planing to include all patched deps into the repo.

cheers

**Comment by ghost** [comment]
ok i try in the afternoon, i'm busy now, thanks for help

**Comment by ghost** [comment]
I have use the erl -pa deps/*/ebin -pa ebin command and shell working now. Thanks to all for the help
