### ISSUE TITLE
illegal instruction (core dumped) 

### ISSUE THREAD

**Issue by djaffarou** [ernw/ss7MAPer#31]
I have installed ss7MAPer on Ubuntu 18.04 LST and when I try to lunch the console it shows me that message :illegal instruction (core dumped) !!!

Did any body known how to fix this issue out there ?

**Comment by 0xc0decafe** [comment]
Hi,

please give me some more information about your setup, as:

- are you running the binary or the source release
- 'uname -a'
- 'erl -version'
- which command did you actually run?

cheers

/daniel

**Comment by 0xc0decafe** [comment]
See #34.
