### ISSUE TITLE
src/ss7MAPer_sup.erl:27: syntax error before: '{'

### ISSUE THREAD

**Issue by yousefElo** [ernw/ss7MAPer#33]
CentOS Linux release 7.6.1810 (Core)

when trying to build rebar code I get below error :

==> ss7MAPer (compile)
Compiled src/hex.erl
Compiled src/sms_7bit_encoding.erl
Compiled src/ss7MAPer.erl
Compiled src/ss7MAPer_app.erl
### **src/ss7MAPer_sup.erl:27: syntax error before: '{'**
src/ss7MAPer_sup.erl:10: function init/1 undefined
ERROR: compile failed while processing /root/ss7MAPer: rebar_abort

**Comment by 0xc0decafe** [comment]
Which erlang version are you using? Try using erlang 18 (see #9)

cheers

**Comment by yousefElo** [comment]
after upgrading erlang I get following error :

ERROR: compile failed while processing /root/ss7MAPer/ss7MAPer/deps/osmo_ss7: rebar_abort
+ cd rel/
+ rebar create-node nodeid=ss7MAPer
==> rel (create-node)
ERROR: Template simplenode not found.
ERROR: 'create-node' failed while processing /root/ss7MAPer/ss7MAPer/rel: rebar_abort
+ cd ..
+ rm deps/signerl/TCAP/ebin/tcap_cco_server.beam
+ rm deps/signerl/TCAP/ebin/tcap_ism_fsm.beam
+ rm deps/signerl/TCAP/ebin/tcap_tco_server.beam
+ rm deps/signerl/TCAP/ebin/tcap_tsm_fsm.beam
+ rm deps/signerl/TCAP/ebin/tcap_dha_fsm.beam
+ rebar generate
==> rel (generate)
==> rel (generate)
ERROR: Unexpected error: {'EXIT',
                             {{badmatch,
                                  {error,
                                      {1,
                                       [99,112,58,32,99,97,110,110,111,116,32,
                                        115,116,97,116,32,226,128,152,47,114,
                                        111,111,116,47,115,115,55,77,65,80,
                                        101,114,47,115,115,55,77,65,80,101,
                                        114,47,114,101,108,47,102,105,108,101,
                                        115,47,101,114,108,226,128,153,58,32,
                                        78,111,32,115,117,99,104,32,102,105,
                                        108,101,32,111,114,32,100,105,114,101,
                                        99,116,111,114,121,10]}}},
                              [{rebar_file_utils,cp_r,2,
                                   [{file,"src/rebar_file_utils.erl"},
                                    {line,68}]},
                               {rebar_reltool,execute_overlay,4,
                                   [{file,"src/rebar_reltool.erl"},
                                    {line,277}]},
                               {rebar_reltool,generate,2,
                                   [{file,"src/rebar_reltool.erl"},{line,57}]},
                               {rebar_core,run_modules,4,
                                   [{file,"src/rebar_core.erl"},{line,404}]},
                               {rebar_core,execute,5,
                                   [{file,"src/rebar_core.erl"},{line,333}]},
                               {rebar_core,process_dir0,6,
                                   [{file,"src/rebar_core.erl"},{line,195}]},
                               {rebar_core,process_each,5,
                                   [{file,"src/rebar_core.erl"},{line,266}]},
                               {rebar_core,process_dir0,6,
                                   [{file,"src/rebar_core.erl"},
                                    {line,171}]}]}}
ERROR: generate failed while processing /root/ss7MAPer/ss7MAPer/rel: rebar_abort

**Comment by 0xc0decafe** [comment]
Hi,

at this point the compilation already succeeded. Your error

> ERROR: Template simplenode not found.

pops up during generation of the standalone binary. I can't tell you, whats wrong with your erlang installation.

cheers
