### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by jennamarble** [ernw/ss7MAPer#35]
if it works in real life scenarios then why the owner is not telling us from where he get access if so he says it works in real life scenarios then why he lie that he doesn't know from where he get access non of us are here to play games with virtual test we want real access or dump your useless project.

**Comment by SigPloiter** [comment]
Because we are responsible on our actions and what we should release and
what not so not anyone can use it in a malicious way :)

**Comment by 0xc0decafe** [comment]
Please stop posting your opinions, this is a software ticketing system and must only be used for bugs found in this software.
This is not a youtube comment!

Also, if you would want you use this software in GRX and you would be in a position were you are allowed to do so, you wouldn't ask questions about the access.

Last but not least, nobody forces you to either checkout or use this software.

best

**Comment by jennamarble** [comment]
so you mean to say that you guys continue to make people stupid? if so i
will keep on posting and exposing this fucking hype created by
motherfuckers like you even if i get banned on github i will keep on making
account to keep on exposing this bullshit project and even if i get banned
on ip level i will keep on changing ip's
