### ISSUE TITLE
Compile Error Fix

### ISSUE THREAD

**Issue by mwsrc** [ernw/ss7MAPer#4]
root@wattos:~/Desktop/ss7MAPer# rebar co
==> pkt (compile)
==> epcap (compile)
Compiling /home/pen/Desktop/ss7MAPer/deps/epcap/c_src/epcap.c
In file included from /home/pen/Desktop/ss7MAPer/deps/epcap/c_src/epcap.c:34:0:
c_src/epcap.h:42:18: fatal error: pcap.h: No such file or directory
compilation terminated.
ERROR: compile failed while processing /home/pen/Desktop/ss7MAPer/deps/epcap: rebar_abort

if users are not use pentest distro like kali or backbox then need pcap.h ( Header File )
So I suggest you add readme. like this
## 

 sudo apt-get install libpcap-dev

Or download this url

http://packages.ubuntu.com/hardy/libpcap-dev
## 

Thanks.

**Comment by 0xc0decafe** [comment]
Hi,

I don't think it is necessary to mention that one needs the pcap header files to build the erlang pcap bindings (; Also the error message is quite clear.
Then your suggested addition is only correct for Ubuntu and I really don't want to add any distribution specific stuff to the README.
Thanks for mentioning, google will find it in this issue.

cheers

**Comment by kaigouthro** [comment]
in brand new Kali, i had this problem, i suggest adding to readme as well. took me over an hour to figure out, and only figured it by seeing this post.

also9, rebar3 is out, should all stuff be updated for that?
