### ISSUE TITLE
osmo_ss7

### ISSUE THREAD

**Issue by luzure** [ernw/ss7MAPer#40]
how to use osmo_ss7 stack on erl from here http://git.osmocom.org/erlang/osmo_ss7 need tutorial i am new to erlang

**Comment by luzure** [comment]
without this it will not work right?

**Comment by 0xc0decafe** [comment]
Hi,

your question is pretty unclear. If you have questions about osmo_ss7, this is not the right place for a ticket.

best

/daniel

**Comment by luzure** [comment]
i do not have questions i just want ss7 stack running

**Comment by luzure** [comment]
can you not help when your program is coded on erlang is entirely new to me thanks that it is precompiled readymade program but osmo_ss7 erlang is not

**Comment by luzure** [comment]
at least tell me from where i can get help running this stack

**Comment by 0xc0decafe** [comment]
Hi,

you might be new to this whole development thingy, so let me tell you something:

This is the ticketing system for a program called ss7MAPer. You are supposed to post bugs, questions and improvements regarding a software called ss7MAPer. If you dont have a question/bug/improvement and/or your question/bug/improvement does not belong to ss7MAPer, this is the wrong place to post.
This is not Youtube and tickets are not comments!

best

**Comment by luzure** [comment]
then fuck this and fuck you and your whole generation that made you waste of sperm

**Comment by luzure** [comment]
i don't know why human being like you born in the first place you are nothing more then trouble to earth first you release a program with no help document second you cannot help someone then in the hell you release such type project basterd
