### ISSUE TITLE
swap don't mount when i start my kali system

### ISSUE THREAD

**Issue by DevilMayCrying** [ernw/ss7MAPer#41]
i extensiten my vmware kali from 30G to 50G, used gparted. but i find when i start my kali, use free -h
![image](https://user-images.githubusercontent.com/24727007/54515946-88c55080-4998-11e9-8fc0-d9d7118427fa.png)
swap don't mount automitic
what should i do to reparire it

**Comment by takeshixx** [comment]
This problem is not related to ss7MAPer.
