### ISSUE TITLE
rebar_core

### ISSUE THREAD

**Issue by Eric534** [ernw/ss7MAPer#5]
Compiled src/sniff.erl
Uncaught error in rebar_core: {'EXIT',
                               {badarg,
                                [{io,format,
                                  [standard_error,
                                   "ERROR: ~p failed while processing ~s: ~s\n",
                                   [compile,
                                    [47,104,111,109,101,47,102,117,47,26700,
                                     38754,47,115,115,55,77,65,80,101,114,47,
                                     100,101,112,115,47,101,112,99,97,112],
                                    [123,
                                     ["'EXIT'",44,
                                      [123,
                                       ["badarg",44,
                                        [91,
                                         [[123,
                                           ["io",44,"format",44,10,
                                            ["  ","  ",32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             ["<0.25.0>",44,
                                              "\"Compiling ~s\n\"",44,10,
                                              [32,"  ","  ",32,
                                               [["  ",32,32],"  ",32,32],
                                               [["  ",32,32],"  ",32,32]],
                                              [91,
                                               [[91,
                                                 ["47",44,"104",44,"111",44,
                                                  "109",44,"101",44,"47",44,
                                                  "102",44,"117",44,"47",44,
                                                  "26700",44,"38754",44,"47",
                                                  44,"115",44,10,
                                                  [32,32,32,"  ","  ",32,
                                                   [["  ",32,32],"  ",32,32],
                                                   [["  ",32,32],"  ",32,32]],
                                                  "115",44,"55",44,"77",44,
                                                  "65",44,"80",44,"101",44,
                                                  "114",44,"47",44,"100",44,
                                                  "101",44,"112",44,"115",44,
                                                  "47",44,"101",44,"112",44,
                                                  10,
                                                  [32,32,32,"  ","  ",32,
                                                   [["  ",32,32],"  ",32,32],
                                                   [["  ",32,32],"  ",32,32]],
                                                  "99",44,"97",44,"112",44,
                                                  "47",44,"99",44,"95",44,
                                                  "115",44,"114",44,"99",44,
                                                  "47",44,"101",44,"112",44,
                                                  "99",44,"97",44,"112",44,
                                                  "46",44,10,
                                                  [32,32,32,"  ","  ",32,
                                                   [["  ",32,32],"  ",32,32],
                                                   [["  ",32,32],"  ",32,32]],
                                                  "99"],
                                                 93]],
                                               93]],
                                             93],
                                            44,10,
                                            ["  ","  ",32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            "[]"],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["rebar_port_compiler",44,
                                            "exec_compiler",44,"4",44,10,
                                            [[32,
                                              [[32,"  ",32,32],32,"  ",32,32],
                                              [32,"  ",32,32],
                                              32,"  ",32,32],
                                             32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             [[123,
                                               ["file",44,
                                                "\"src/rebar_port_compiler.erl\""],
                                               125],
                                              44,10,
                                              [32,
                                               [32,
                                                [[32,"  ",32,32],
                                                 32,"  ",32,32],
                                                [32,"  ",32,32],
                                                32,"  ",32,32],
                                               32,
                                               [["  ",32,32],"  ",32,32],
                                               [["  ",32,32],"  ",32,32]],
                                              [123,["line",44,"294"],125]],
                                             93]],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["rebar_port_compiler",44,
                                            "compile_each",44,"5",44,10,
                                            [[32,
                                              [[32,"  ",32,32],32,"  ",32,32],
                                              [32,"  ",32,32],
                                              32,"  ",32,32],
                                             32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             [[123,
                                               ["file",44,
                                                "\"src/rebar_port_compiler.erl\""],
                                               125],
                                              44,10,
                                              [32,
                                               [32,
                                                [[32,"  ",32,32],
                                                 32,"  ",32,32],
                                                [32,"  ",32,32],
                                                32,"  ",32,32],
                                               32,
                                               [["  ",32,32],"  ",32,32],
                                               [["  ",32,32],"  ",32,32]],
                                              [123,["line",44,"251"],125]],
                                             93]],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["lists",44,"foldl",44,"3",44,
                                            [91,
                                             [[123,
                                               ["file",44,"\"lists.erl\""],
                                               125],
                                              44,
                                              [123,["line",44,"1262"],125]],
                                             93]],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["rebar_port_compiler",44,
                                            "compile_sources",44,"3",44,10,
                                            [[32,
                                              [[32,"  ",32,32],32,"  ",32,32],
                                              [32,"  ",32,32],
                                              32,"  ",32,32],
                                             32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             [[123,
                                               ["file",44,
                                                "\"src/rebar_port_compiler.erl\""],
                                               125],
                                              44,10,
                                              [32,
                                               [32,
                                                [[32,"  ",32,32],
                                                 32,"  ",32,32],
                                                [32,"  ",32,32],
                                                32,"  ",32,32],
                                               32,
                                               [["  ",32,32],"  ",32,32],
                                               [["  ",32,32],"  ",32,32]],
                                              [123,["line",44,"220"],125]],
                                             93]],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["rebar_port_compiler",44,
                                            "compile",44,"2",44,10,
                                            [[32,
                                              [[32,"  ",32,32],32,"  ",32,32],
                                              [32,"  ",32,32],
                                              32,"  ",32,32],
                                             32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             [[123,
                                               ["file",44,
                                                "\"src/rebar_port_compiler.erl\""],
                                               125],
                                              44,10,
                                              [32,
                                               [32,
                                                [[32,"  ",32,32],
                                                 32,"  ",32,32],
                                                [32,"  ",32,32],
                                                32,"  ",32,32],
                                               32,
                                               [["  ",32,32],"  ",32,32],
                                               [["  ",32,32],"  ",32,32]],
                                              [123,["line",44,"58"],125]],
                                             93]],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["rebar_core",44,"run_modules",44,
                                            "4",44,10,
                                            [[["   ",32,32,32],"   ",32,32,32],
                                             32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             [[123,
                                               ["file",44,
                                                "\"src/rebar_core.erl\""],
                                               125],
                                              44,
                                              [123,["line",44,"493"],125]],
                                             93]],
                                           125],
                                          44,10,
                                          [32,
                                           [["  ",32,32],"  ",32,32],
                                           [["  ",32,32],"  ",32,32]],
                                          [123,
                                           ["rebar_core",44,"execute",44,"6",
                                            44,10,
                                            [[["   ",32,32,32],"   ",32,32,32],
                                             32,
                                             [["  ",32,32],"  ",32,32],
                                             [["  ",32,32],"  ",32,32]],
                                            [91,
                                             [[123,
                                               ["file",44,
                                                "\"src/rebar_core.erl\""],
                                               125],
                                              44,
                                              [123,["line",44,"418"],125]],
                                             93]],
                                           125]],
                                         93]],
                                       125]],
                                     125]]],
                                  []},
                                 {rebar_utils,abort,2,
                                  [{file,"src/rebar_utils.erl"},{line,220}]},
                                 {rebar_core,maybe_execute,8,
                                  [{file,"src/rebar_core.erl"},{line,302}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,261}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]}]}}

Why this error occurs.

Could you help me, please.

Erlang/OTP 18 [erts-7.0] [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.0  (abort with ^G)

**Comment by 0xc0decafe** [comment]
Hi,
this is a problem with epcap, not ss7MAPer.
Maybe you should file a bug there.

cheers

**Comment by Eric534** [comment]
Can you help me to solve it
