### ISSUE TITLE
epcap

### ISSUE THREAD

**Issue by Eric534** [ernw/ss7MAPer#6]
epcap can not find
git.osmocom.org/erlang/epcap     There is no file.

Can you give me a pass

I found a epcap on the Internet.

But this error has occurred.
Uncaught error in rebar_core: {'EXIT',
                               {badarg,
                                [{io,format,
                                  [standard_io,
                                   "WARN:  ~s has version ~p; requested regex was ~s\n",
                                   [[47,104,111,109,101,47,106,97,99,107,47,
                                     26700,38754,47,115,115,55,77,65,80,101,
                                     114,47,100,101,112,115,47,101,112,99,97,
                                     112,47,115,114,99,47,101,112,99,97,112,
                                     46,97,112,112,46,115,114,99],
                                    "0.8.1","0.03"]],
                                  []},
                                 {rebar_deps,is_app_available,5,
                                  [{file,"src/rebar_deps.erl"},{line,482}]},
                                 {rebar_deps,find_dep_in_dir,3,
                                  [{file,"src/rebar_deps.erl"},{line,440}]},
                                 {rebar_deps,find_deps,4,
                                  [{file,"src/rebar_deps.erl"},{line,399}]},
                                 {rebar_deps,preprocess,2,
                                  [{file,"src/rebar_deps.erl"},{line,67}]},
                                 {rebar_core,acc_modules,5,
                                  [{file,"src/rebar_core.erl"},{line,540}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,237}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]}]}}

**Comment by 0xc0decafe** [comment]
Cannot reproduce:

```
$ rebar get-deps
==> ss7MAPer (get-deps)
Pulling osmo_ss7 from {git,"git://git.osmocom.org/erlang/osmo_ss7/","master"}
Cloning into 'osmo_ss7'...
Pulling osmo_sccp from {git,"git://git.osmocom.org/erlang/osmo_sccp/",
                            "master"}
Cloning into 'osmo_sccp'...
Pulling osmo_map from {git,"git://git.osmocom.org/erlang/osmo_map/","master"}
Cloning into 'osmo_map'...
==> rel (get-deps)
==> osmo_ss7 (get-deps)
Pulling epcap from {git,"git://git.osmocom.org/erlang/epcap","master"}
Cloning into 'epcap'...
==> epcap (get-deps)
Pulling pkt from {git,"git://github.com/msantos/pkt.git","master"}
Cloning into 'pkt'...
==> pkt (get-deps)
==> osmo_sccp (get-deps)
==> osmo_map (get-deps)
$
```

**Comment by 0xc0decafe** [comment]
```
$ git clone git://git.osmocom.org/erlang/epcap
Cloning into 'epcap'...
remote: Counting objects: 335, done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 335 (delta 174), reused 335 (delta 174)
Receiving objects: 100% (335/335), 129.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (174/174), done.
Checking connectivity... done.
```
