### ISSUE TITLE
not compiling on kali linux 2016.2

### ISSUE THREAD

**Issue by AnoBuUu** [ernw/ss7MAPer#7]
last kali version, last updates

erlang version (1:19.0.7+dfsg-1)
rebar 2.6.2 18 20160823_165807 

*\* ERROR in parse_transform function:
**\* Reason     = function_clause
**\* Location: {exprecs,403}
**\*       type = function
**\*    context = {context,osmo_util,undefined,undefined}
**\*        acc = {pass1,
                     [primitive],
                     false,
                     [{pointcode,
                          [{typed_record_field,
                               {record_field,15,{atom,15,repr}},
                               {user_type,15,pointcode_repr,[]}},
                           {record_field,16,{atom,16,value}}]},
                      {primitive,
                          [{record_field,6,{atom,6,subsystem}},
                           {record_field,7,{atom,7,gen_name}},
                           {typed_record_field,
                               {record_field,8,{atom,8,spec_name}},
                               {user_type,8,prim_spec_name,[]}},
                           {record_field,9,{atom,9,parameters}}]}]}
**\*       form = {function,51,digit_list2int,2,
                     [{clause,51,
                          [{var,51,'Int'},{nil,51}],
                          [],
                          [{var,52,'Int'}]},
                      {clause,53,
                          [{var,53,'Int'},
                           {cons,53,{var,53,'Digit'},{var,53,'Tail'}}],
                          [],
                          [{call,54,
                               {atom,54,digit_list2int},
                               [{op,54,'+',
                                    {op,54,'*',{var,54,'Int'},{integer,54,10}},
                                    {var,54,'Digit'}},
                                {var,54,'Tail'}]}]}]}
/root/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl:51: function_clause
Compiling /root/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl failed:
ERROR: compile failed while processing /root/ss7MAPer/deps/osmo_ss7: rebar_abort

**Comment by 0xc0decafe** [comment]
Hi,

please try a stable erlang version, eg. 18.x, as version 19 is unsupported.

cheers

**Comment by 0xc0decafe** [comment]
Also, please take the time and add _at least_ one complete sentence to your bug description.

cheers

**Comment by AnoBuUu** [comment]
Compiled src/sctp_m2pa.erl
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:22: Warning: undefined callback function handle_sync_event/4 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:22: Warning: undefined callback function state_change/2 (behaviour 'sctp_core')
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:72: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:77: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:80: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:87: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:97: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:138: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:145: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:153: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:160: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:167: Warning: variable 'State' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:207: Warning: variable 'M2ua' is unused
/root/ss7MAPer/deps/osmo_ss7/src/sctp_m2ua.erl:208: Warning: variable 'State' is unused
Compiled src/sctp_m2ua.erl
**\* ERROR in parse_transform function:
**\* Reason     = function_clause
**\* Location: {exprecs,403}
**\*       type = function
**\*    context = {context,osmo_util,undefined,undefined}
**\*        acc = {pass1,
                     [primitive],
                     false,
                     [{pointcode,
                          [{typed_record_field,
                               {record_field,15,{atom,15,repr}},
                               {user_type,15,pointcode_repr,[]}},
                           {record_field,16,{atom,16,value}}]},
                      {primitive,
                          [{record_field,6,{atom,6,subsystem}},
                           {record_field,7,{atom,7,gen_name}},
                           {typed_record_field,
                               {record_field,8,{atom,8,spec_name}},
                               {user_type,8,prim_spec_name,[]}},
                           {record_field,9,{atom,9,parameters}}]}]}
**\*       form = {function,51,digit_list2int,2,
                     [{clause,51,
                          [{var,51,'Int'},{nil,51}],
                          [],
                          [{var,52,'Int'}]},
                      {clause,53,
                          [{var,53,'Int'},
                           {cons,53,{var,53,'Digit'},{var,53,'Tail'}}],
                          [],
                          [{call,54,
                               {atom,54,digit_list2int},
                               [{op,54,'+',
                                    {op,54,'*',{var,54,'Int'},{integer,54,10}},
                                    {var,54,'Digit'}},
                                {var,54,'Tail'}]}]}]}
/root/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl:51: function_clause
Compiling /root/ss7MAPer/deps/osmo_ss7/src/osmo_util.erl failed:
ERROR: compile failed while processing /root/ss7MAPer/deps/osmo_ss7: rebar_abort

**Comment by 0xc0decafe** [comment]
No sentence, no help....
Closed.
