### ISSUE TITLE
error ei.h

### ISSUE THREAD

**Issue by Eric534** [ernw/ss7MAPer#8]
Compiling /root/Desktop/ss7MAPer/deps/epcap/c_src/epcap.c
root/Desktop/ss7MAPer/deps/epcap/c_src/epcap.c:32:16: fatal error: ei.h:No such file or directory
comoilation terminated.
ERROR:compile failed while processing /root/Desktop/ss7MAPer/deps/epcap/c_src/epcap: rebar_avort

Which file is ei.h?
erlang is 18
Ei.h is not a library file for Erlang？？

**Comment by 0xc0decafe** [comment]
Hi,

the file is present in two locations on my system:

/usr/lib64/erlang/usr/include/ei.h
/usr/lib64/erlang/lib/erl_interface-3.8.2/include/ei.h

and it seams to be part of erlang.

it would be helpfull if you could tell me which operating system you are on.

cheers

**Comment by Eric534** [comment]
Hi,
My system is Linux Kali

ei.h I found it in the Erlang directory.

**Comment by Eric534** [comment]
Hi,
Can you give me a copy of your compile? 
I do not know where it is not set, has been unable to compile

**Comment by Eric534** [comment]
Hi,

Can I compile static?
I might need to go somewhere else.
If every place I have installed, the process is too cumbersome

My previous error was due to the Erlang compiler environment is wrong,
 but I did not find a specific error

**Comment by 0xc0decafe** [comment]
Hi,

I'm currently working on a binary release, stay tuned.

cheers

**Comment by Eric534** [comment]
Hi,

This program is not to be used in the Erlang environment.
But rebar Erlang environment I configuration is always wrong.

**Comment by 0xc0decafe** [comment]
Hi,

you can try the first binary test build, find it here:

https://c0decafe.de/tools/ss7MAPer_alpha1_linux_x64.tar.bz2

cheers

**Comment by 0xc0decafe** [comment]
Binary build released.

**Comment by OctAg0nO** [comment]
running Binary build get this error

./bin/ss7MAPer console
Exec: /root/ss7MAPer/erts-7.3/bin/erlexec  -boot /root/ss7MAPer/releases/1/ss7MAPer -mode embedded -config /root/ss7MAPer/releases/1/sys.config -args_file /root/ss7MAPer/releases/1/vm.args -- console
Root: /root/ss7MAPer
/root/ss7MAPer/erts-7.3/bin/erlexec: 1: /root/ss7MAPer/erts-7.3/bin/erlexec: ELF: not found
/root/ss7MAPer/erts-7.3/bin/erlexec: 2: /root/ss7MAPer/erts-7.3/bin/erlexec: Syntax error: "(" unexpected

**Comment by jingxizhu** [comment]
how do you fix this Error?
